services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: my_blog_db
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: blog_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: